### ISSUE TITLE
Missing Documentation for gprm Dependency

### ISSUE THREAD

**Issue by WalterXL** [siwill22/molchan#1]
Thank you for providing this excellent code repository. I noticed that the code heavily relies on a package named `gprm` (e.g., imports such as `gprm.PointDistributionOnSphere` and utilities from `gprm.utils`), but I couldn't find any information about this library in the repository or online.

Could you please provide:
1. A description of `gprm`, its purpose, and how it integrates with the current repository.
2. Installation instructions for `gprm` (e.g., whether it is an internal module, available via PyPI, or needs to be built separately).
3. Any additional documentation or references for `gprm` usage.

This information would be very helpful for replicating your work and understanding the code.

Thank you for your time and assistance!

Best regards,  
Walter

**Comment by siwill22** [comment]
Hi Walter,

gprm is an abbreviation for GPlatesReconstructionModel, which is a set of python tools to make working with GPlates-format plate tectonic reconstructions easier.

You can find the code, additional dependencies, and installation instructions here:
https://github.com/siwill22/GPlatesReconstructionModel

Hope that helps,
Simon

**Comment by WalterXL** [comment]
Hi Simon,  

Thank you for your detailed response and for sharing the link to the repository. I’ll take a closer look and reach out if I have any further questions.  

Best regards,  
Walter
